
# Q1. Array Creation and Attributes

## Problem Statement
Create array [10,20,30,40,50] and print shape, ndim, size and dtype.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [2]:
import numpy as np
a = np.array([10,20,30,40,50])
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(5,)
1
5
int64



# Q2. Matrix Creation

## Problem Statement
Create a 3x3 NumPy matrix and print it.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [4]:
arr = np.random.randint(1,17,(4,4))
print(arr)

[[ 9 16  2 12]
 [10 14  5 13]
 [14  9  7  3]
 [10  1 11  7]]



# Q3. Indexing Practice

## Problem Statement
Print first, third and last element from an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [7]:
import numpy as np
a = np.array([10,20,30,40,50])
print(a[-1])
print(a[2])


50
30



# Q4. Slicing Practice

## Problem Statement
Print elements from index 2 to 5.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [11]:
arr = np.array([1,2,3,4,5,6])
print(arr[1:5])

[2 3 4 5]



# Q5. Fancy Indexing

## Problem Statement
Print selected elements using fancy indexing.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [12]:
import numpy as np
a = np.array([10,20,30,40,50])
print(a[[-1,3,2]])

[50 40 30]



# Q6. Conditional Selection

## Problem Statement
Print values greater than 15.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [25]:
b = np.array([5,10,15,20,25,30,45,50,60])
print(b[np.where(b > 15)])

[20 25 30 45 50 60]



# Q7. Broadcasting

## Problem Statement
Add 10 to every element of an array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [10]:
import numpy as np
arr = np.array([11,22,33,44,55])
print(a+10)

[20 30 40 50 60]



# Q8. Aggregate Functions

## Problem Statement
Print sum, mean, max and min.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [6]:
import numpy as np
a = np.array([10,20,30,40,50])
print(f'sum is: {a.sum()}')
print(f'sum is: {a.mean()}')
print(f'sum is: {a.min()}')
print(f'sum is: {a.max()}')

sum is: 150
sum is: 30.0
sum is: 10
sum is: 50



# Q9. Sorting

## Problem Statement
Sort an unsorted NumPy array.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [11]:
e = np.array([6,8,3,9,2,1])
print(np.sort(e))

[1 2 3 6 8 9]



# Q10. Concatenation and Stacking

## Problem Statement
Perform concatenate and vstack on two arrays.

## Sample Input
```python
Use NumPy arrays
```

## Sample Output
```python
Expected Output
```


In [13]:
a =np.array([1,2,3,4,5])
b= np.array([6,7,8,9,10])
print(np.concatenate((a,b)))
print(np.vstack((a,b)))

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
